Implemented IWordReplacer to handle different types of profanity replacement
IEvangelist/GitHub.ProfanityFilter pull request #15
Opened 2019-09-12 01:34 UTC by bepursuant

Implemented injectable WordReplacer to handle different types of profanity replacement, and created a new WordReplacer based on the Orbit "Lint Licker" commercial ( https://www.youtube.com/watch?v=5ssytWYn6nY )

v1.1.0.0
--------
* Updated Sandbox Application to netcoreapp3.0, as I didnt have 2.2 available on my machine
* Added IWordReplacer interface and injected it in the service configuration
* Moved GitHubEmoji to GitHubEmojiWordReplacer, which implements the IWordReplacer interface (see known issues below)
* Added a LintLickerWordReplacer implementation of the IWordReplacer, with a basic list of words from the commercial
* Added IWordReplacer to ProfanityFilter constructor, and removed previous GitHubEmoji selection logic in favor of calling the injected IWordReplacer.ReplaceWord method

Known Issues
------------
* Because the logic with selection of words has changed, the previous behavior that preferred to not reuse words is now broken, and this update is more likely to reuse a word than the previous version. The IWordReplacers were implemented as singletons instead of static classes so that they can, with an update, store a list of used words/emoji so that they can prefer to not reuse them in the future

Potential Enhancements
----------------------
* Now that the IWordReplacer knows the word it is replacing, it could select the most appropriate word (ex. replace **f**word with a flower emoji, or the word **f**ork/**f**rench-toast
* Tagging words in InappropriateLanguage with their part of speech (verb, adjective, noun) could allow a WordReplacer to provide a replacement that fits better into the original text
* A 'MappedProfaneWordReplacer' could be implemented that would replace words with 'less offensive' versions of themselves (ex pi**ed to perturbed)
* A more practical version of LintLicker could provide words, not based on the commercial, that would also work well - ex fork, flip, shoot, snap... but would probably be best in conjunction with an implementation of parts of speech tagging

2019-09-12 01:38 UTC, bepursuant commented
I was only able to run the tests to validate this - the sandbox cannot run due to GQL connection issues (I don't have a GQL connection...). Tests did pass after I passed in a specific IWordReplacer into the ProfanityFilter constructor, but I can't be sure that I implemented the Dependency Injection correctly in the actual service.

Also, how would we make the WordReplacer actually user-configurable? It seems like that shouldn't depend on being injected statically - I'm actually not sure that 'injection' is the most appropriate approach for that type of mechanism?

2019-09-12 12:57 UTC, IEvangelist requested changes
Hi @bepursuant,

Thank you for your pull request, I ❤️ it. I wanted to propose a few things as a counter to this feature addition. The API needs to be reconsidered a bit and we need to keep the unique logic intact. See my comments.

Thanks again,
David Pine

2019-09-12 12:57 UTC, IEvangelist commented on IEvangelist.GitHub.Sandbox/IEvangelist.GitHub.Sandbox.csproj
> +    <TargetFramework>netcoreapp3.0</TargetFramework>
Unfortunately, we can't do .NET Core 3.0 yet as Azure Functions do not natively support it yet. I tried and it involved too much hand holding.  Please revert to 2.2

2019-09-12 12:57 UTC, IEvangelist commented on IEvangelist.GitHub.Services/Filters/GitHubEmojiWordReplacer.cs
> +        public string ReplaceWord(string word)
This could simply be an expression and for this project, that is what I'd prefer.

```csharp
public string ReplaceWord(string word) => Emoji.GetRandomElement();
```

2019-09-12 12:57 UTC, IEvangelist commented on IEvangelist.GitHub.Services/Filters/LintLickerWordReplacer.cs
> +        public string ReplaceWord(string word)
Again, I prefer an expression here please.

2019-09-12 12:57 UTC, IEvangelist commented on IEvangelist.GitHub.Services/Filters/IWordReplacer.cs
> +        string ReplaceWord(string word);
Ah, now I see the intent of this... I think we should change this API ever so slightly. Ideally, these should really just be replacement option lists, not a function to replace a word. They actually don't do anything with the word they are given. Perhaps, this API could be more like this:

```csharp
public interface IWordReplacementProvider
{
    IEnumerable<string> GetReplacements(int numberOfWordsToReplace);
}
```

The the implementations would ensure random ordering, and provide unique words given the number of words to replace.

2019-09-12 12:57 UTC, IEvangelist commented on IEvangelist.GitHub.Services/Filters/ProfanityFilter.cs
The logic that was removed here was a vital part of the implementation, it ensured that replacements were unique and I'd like to try to keep that logic intact. With the proposed changes to the interface you provided this would be easy to achieve.

Instead of using the hardcoded `GitHubEmoji.ProfaneReplacements`, we'd use the corresponding implementation of the `IWordReplacementProvider.GetReplacements` and give it the `profaneCount` variable. Make sense?

2019-09-12 13:27 UTC, IEvangelist commented
I like the **potential enhancements**, and I too had several of these ideas. As for the configuration aspect of it, I can handle that once this is pull request is merged. It's rather straightforward and I'll share it with you once it is committed.

I love the idea of mapping explicit word replacement instead of being random. That feels more appropriate, which leads to a question. Should every entry in the `InappropriateLanguage` have a mapped `int` value that represents it as an identifier? For example, all the variations of the "f" word would map to `1` then replacement providers could look up their corresponding replacement for that id?

2019-09-13 01:14 UTC, bepursuant commented on IEvangelist.GitHub.Sandbox/IEvangelist.GitHub.Sandbox.csproj
> +    <TargetFramework>netcoreapp3.0</TargetFramework>
Resolved in commit 640763.

2019-09-13 01:14 UTC, bepursuant commented on IEvangelist.GitHub.Services/Filters/GitHubEmojiWordReplacer.cs
> +        public string ReplaceWord(string word)
Resolved in commit 640763.

2019-09-13 01:15 UTC, bepursuant commented on IEvangelist.GitHub.Services/Filters/LintLickerWordReplacer.cs
> +        public string ReplaceWord(string word)
Resolved in commit 640763.

2019-09-13 01:19 UTC, bepursuant commented on IEvangelist.GitHub.Services/Filters/IWordReplacer.cs
> +        string ReplaceWord(string word);
I implemented a quick usage of the word parameter in the LintLicker.ReplaceWord method, so it now prefers to select a word that starts with the same letter as the profane word. Because we're selecting a word based on the word it is replacing, I think it'll need to be passed into the ReplaceWord method, and therefore should be a method?

2019-09-13 01:21 UTC, bepursuant commented on IEvangelist.GitHub.Services/Filters/ProfanityFilter.cs
I found an issue with the current GetRandomElements() implementation, in that if the number of random elements exceeds the available options, an exception will be thrown due to the queue being empty. I think (haven't tested it) that this means if an issue had more than 75 profane words, the filter would just throw an exception and the replacement wouldn't be completed?

I'll have to think about how to address this - would storing a count of usages of each Emoji / word and sorting by that be an appropriate way to _prefer_ an unused word, but not cause an issue if we need to use more than the available options?

2019-09-13 01:28 UTC, IEvangelist approved these changes

2019-09-13 01:28 UTC, merged

2019-09-13 01:34 UTC, bepursuant commented
Sorry for the comment spam - I'm not sure exactly how these types of suggestions are usually commented on or who clicks the "Resolve" button for them...

Regarding inappropriate language replacement words, I suspect the best approach may be to have the InappropriateLanguage be a List of profane words as a struct or class (or just a Dictionary<string, Regex), each containing a 'word' and a 'regex' property for matching.

This would work similar to your suggestion, but the WordReplacer could map the plaintext 'word' to a replacement word (or words), as opposed to mapping to an arbitrary/magic integer... but would have the advantage of reducing the number of regexes to evaluate, and giving them a contextual "id", being the base word?
![image](https://user-images.githubusercontent.com/10257655/64831736-9c92ed80-d59c-11e9-9c71-c88e8d2ede20.png)

2019-09-13 01:38 UTC, IEvangelist commented
Typically, these kinds of suggestions could be entered as an issue and then I could start labeling them appropriately. And we could discuss them there. BTW, were you at my talk or how did you discover this project?